# Generated by Django 5.1.3 on 2025-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tijdstip', models.DateTimeField(auto_now_add=True)),
                ('teller', models.IntegerField()),
                ('regenval', models.FloatField()),
            ],
        ),
    ]
