# Generated by Django 5.1.3 on 2025-02-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weerstation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegenMeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tijdstip', models.DateTimeField(auto_now_add=True)),
                ('regenval', models.FloatField(help_text='Regenval in mm')),
            ],
        ),
    ]
