# Generated by Django 5.1.3 on 2025-02-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weerstation', '0002_regenmeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegenData',
        ),
    ]
