# Generated by Django 5.1.3 on 2025-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weerstation', '0003_delete_regendata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindMeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tijdstip', models.DateTimeField(auto_now_add=True)),
                ('windsnelheid', models.FloatField(help_text='snelheid in km/h')),
            ],
        ),
    ]
