# Generated by Django 5.1.3 on 2025-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weerstation', '0005_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regenmeting',
            name='tijdstip',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='windmeting',
            name='tijdstip',
            field=models.DateTimeField(blank=True),
        ),
    ]
