# Generated by Django 5.1.3 on 2025-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weerstation', '0006_alter_regenmeting_tijdstip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
