# Generated by Django 5.1.3 on 2025-03-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weerstation', '0007_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindMeting',
        ),
    ]
